name:               "Ink"
description:        "rafalab"

site.name	    "rafalab"
author:             "rafalab"
twitter:            "rafalab"
github:             "rafalab"


background:         "http://docs.oracle.com/javafx/2/get_started/background.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            "http://rafalab.github.io"

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate